### ISSUE TITLE
Illustrations

### ISSUE THREAD

**Issue by OVerontsova** [november-kilo/PFiSci#7]
This document needs them :chart_with_upwards_trend: :chart_with_downwards_trend: :bar_chart:

**Comment by november-kilo** [comment]
:+1:

**Comment by OVerontsova** [comment]
Also: I don't like how unit vectors look. Should experiment with their look and feel.

**Comment by november-kilo** [comment]
Gonna close this. Added several illustrations, fixed unit vectors. We can be more specific when opening issues like this going forward.
